version: '3'
services:
  ghost:
    image: ghost
    volumes:
      - ${SERVICE_GHOST_VOLUME}
    ports:
      - ${SERVICE_GHOST_PORT}
    environment:
      - NODE_ENV=production
    restart: on-failure

  nginx:
    image: nginx
    volumes:
      - /opt/nginx/config:/etc/nginx/conf.d
      - /opt/nginx/logs:/etc/nginx/logs
      - /opt/letsencrypt/certbot:/etc/letsencrypt
    links:
      - ghost
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure

  certbot:
    image: certbot/certbot
    volumes:
      - /opt/letsencrypt/certbot:/etc/letsencrypt
      - /opt/letsencrypt/logs:/var/log/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    command: certonly --standalone --non-interactive --agree-tos --email=${SERVICE_CERTBOT_EMAIL} ${SERVICE_CERTBOT_DOMAINS}